### ISSUE TITLE
No Planetary Computer access

### ISSUE THREAD

**Issue by matt-skiff** [cordmaur/Sentinel1-Flood-Finder#1]
Hi there,

Signups for the Planetary Computer are closed AFAIK
Is there a way to use your package without needing this API?

Cheers,
Matthew Skiffington

**Comment by cordmaur** [comment]
@matt-skiff , since the shutdown of the HUB they removed the necessity for they Key. 
I removed the subscription key from the FloodProcessor Constructor and re-tested the introduction notebook.
Can you try running it again?

**Comment by matt-skiff** [comment]
Thank you very much @cordmaur, it works great!

**Comment by matt-skiff** [comment]
Resolved
